services:
  - type: web
    name: gen-music
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
